### ISSUE TITLE
launchtask读不出来

### ISSUE THREAD

**Issue by ys2013** [ruzhuxiaogu/RZLauncher#1]
按照demo 的样子去写的，是不是有什么其他的配置

可能存在task section存在于多个多个image中，这样一次读取，并不能将所有的task都读出来，建议监听image的加载回调，然后通过回调的mh进行section内task的采集

**Comment by ruzhuxiaogu** [comment]
现在中间件部分是image加载之后读取的，可以发一下你的注册代码看下

**Comment by ruzhuxiaogu** [comment]
我们这边是OK的

**Comment by ruzhuxiaogu** [comment]
也可以直接发一下demo哈

**Comment by ys2013** [comment]
> 也可以直接发一下demo哈

https://github.com/ys2013/rzlauncher-demo.git 还请不吝赐教

**Comment by ys2013** [comment]
请问有新的进展吗，能加个微信聊聊吗

**Comment by ruzhuxiaogu** [comment]
> 请问有新的进展吗，能加个微信聊聊吗
podfile中去掉use_frameworks!

**Comment by ruzhuxiaogu** [comment]
这块我后续继续优化一下

**Comment by ys2013** [comment]
> > 请问有新的进展吗，能加个微信聊聊吗
> > podfile中去掉use_frameworks!

我测试了下，发现去掉后确实好使了， 但是镜像的加载顺序和这个的关联我没搞明白，
还有一点，去掉后，这样限制了use_framework!的使用，有些需要动态库的场景还是需要的

**Comment by ruzhuxiaogu** [comment]
> > > 请问有新的进展吗，能加个微信聊聊吗
> > > podfile中去掉use_frameworks!
> 
> 我测试了下，发现去掉后确实好使了， 但是镜像的加载顺序和这个的关联我没搞明白，
> 还有一点，去掉后，这样限制了use_framework!的使用，有些需要动态库的场景还是需要的

可以用cocoapods-packing-cubes去指定动态库和非动态库
