### ISSUE TITLE
检测依赖是不是有点bug？

### ISSUE THREAD

**Issue by ma125125t** [ruzhuxiaogu/RZLauncher#2]
例如，在demo中将RZAppLaunchTask5的依赖设置为`@[@"RZAppLaunchTask3,RZAppLaunchTask7"];`崩溃，显示存在依赖，不过事实上并不存在依赖。

另外，还有个疑问，如果一个任务需要立即执行，而该任务的依赖是runloop空闲执行，这时候会发生什么？该线程会等待吗？

我自己测试了下，这个Immediately的任务不会执行哦。

**Comment by ruzhuxiaogu** [comment]
1.我这边改成@[@"RZAppLaunchTask3,RZAppLaunchTask7"];，没有走到assert里，再检查下是否有循环依赖，另外RZLaunchTask.plist中也有设置依赖。
2.会在runloop空闲的时候立即执行。

**Comment by ma125125t** [comment]
有空加个微信不？我把我修改的项目发你？

**Comment by ma125125t** [comment]
```
- (BOOL)runForLaunchLife:(NSInteger)life{
    if (life == RZLaunchLife_DidBecomeActive) {
        NSLog(@"RZAppLaunchTask8 finished in Thread:%@", [NSThread currentThread]);
    }
    return YES;
}

- (BOOL)runImmediatelyForLaunchLife:(NSInteger)life {
    return YES;
}

- (RZLaunchThread)runInThreadForLaunchLife:(NSInteger)life{
    return RZLaunchThread_Work;
}
```

```
- (BOOL)runForLaunchLife:(NSInteger)life{
    if (life == RZLaunchLife_DidBecomeActive) {
        NSLog(@"RZAppLaunchTask9 finished in Thread:%@", [NSThread currentThread]);
    }
    return YES;
}

- (BOOL)runImmediatelyForLaunchLife:(NSInteger)life {
    return NO;
}

- (RZLaunchThread)runInThreadForLaunchLife:(NSInteger)life{
    return RZLaunchThread_Main;
}

- (NSArray<NSString *> *)runPredecessorsForLaunchLife:(NSInteger)life{
    return @[@"RZAppLaunchTask8"];
}
```

我这边比如这样添加task，task8是不会执行的

**Comment by ma125125t** [comment]
理论上run immediate的任务和空闲时调用是冲突的

**Comment by ruzhuxiaogu** [comment]
RZLAUNCH_REGISTER(RZAppLaunchTask1) 头文件的注解加了吗，这个是注册的关键

**Comment by ma125125t** [comment]
嗯，加了的

**Comment by ruzhuxiaogu** [comment]
发我邮箱吧？m18354276092@163.com

**Comment by ma125125t** [comment]
已发送

**Comment by ruzhuxiaogu** [comment]
我看了下，runImmediately和RZLaunchThread_Work是互斥的两个配置，RZLaunchThread_Work代表不一定会立即执行。runImmediately可以和RZLaunchThread_Main搭配使用。

**Comment by ma125125t** [comment]
打扰了，又修改了一些代码，将9的依赖设置为8，结果是9比8先执行。还请赐教。

**Comment by ruzhuxiaogu** [comment]
RZLaunchThread_Main 和 RZLaunchPriority搭配使用，因为main thread上肯定是串行的，RZLaunchThread_Work和runPredecessorsForLaunchLife搭配使用，因为是并行的。
